# Generated by Django 5.0 on 2023-12-18 16:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuietZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the quiet zone', max_length=200)),
                ('description', models.TextField(help_text='Description of the quiet zone')),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Geographic location (longitude, latitude)', srid=4326)),
                ('noise_level', models.DecimalField(decimal_places=1, help_text='Average noise level rating', max_digits=2)),
                ('amenities', models.JSONField(blank=True, help_text='JSON structure of amenities offered', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time this record was last updated.')),
            ],
            options={
                'verbose_name_plural': 'Quiet Zones',
            },
        ),
    ]
