# Generated by Django 5.0 on 2023-12-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='quietzone',
            name='average_rating',
            field=models.FloatField(default=0, help_text='Average user rating'),
        ),
        migrations.AddField(
            model_name='quietzone',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for categorizing quiet zones', related_name='quiet_zones', to='ca2.tag'),
        ),
    ]
